language: node_js
node_js:
  - 6
  - 8
sudo: false
notifications:
  email:
    recipients:
      - ladislav@prskavec.net
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
